name: Test (dev)

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - uses: tlienart/xranklin-build-action@dev
        with:
          SITE_FOLDER: "test/"
          DEPLOY: false
          ARTIFACTS: true
          LUNR: true
