name: Test

on:
  push:
    branches:
      - dev
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - uses: tlienart/xranklin-build-action@main
        with:
          SITE_FOLDER: "test/"
          DEPLOY: false
